# permissions for end users to edit slacknotifications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slacknotification-editor-role
rules:
- apiGroups:
  - eventnotifier.drhelius.io
  resources:
  - slacknotifications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventnotifier.drhelius.io
  resources:
  - slacknotifications/status
  verbs:
  - get
